# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_contacto', models.CharField(default='000000000', max_length=9)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_post', models.CharField(default='Vendo Vehiculo', max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.PositiveIntegerField()),
                ('fecha_itv_valida', models.DateTimeField()),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeRu.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_vehiculo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.TextField()),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeRu.Vehiculo'),
        ),
    ]
